name: graph_vae_py3.6_pt1.1
channels:
  - rdkit
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - ipykernel=5.1.0
  - ipython=7.4.0
  - jupyter=1.0.0
  - matplotlib=3.0.3
  - networkx=2.2
  - numpy=1.16.2
  - pip=19.0
  - pytest=4.3.1
  - scipy=1.2.1
  - seaborn=0.9.0
  - six=1.12.0
  - rdkit=2019.03.3
  - pytorch==1.1
  - torchvision==0.3
  - pip:
    - arrow==0.14.2
    - dataclasses==0.6
    - docopt==0.6.2
    - tensorboardx==1.8
    - tqdm==4.32.2
